######################################################################
#  Project
######################################################################

BINARY		= bareblink
SRCFILES	= main.c 

all: elf bin

include ../Makefile.incl

# End
