######################################################################
#  Project
######################################################################

BINARY		= uart_tempsensoradc
SRCFILES	= main.c 

all: elf bin

include ../Makefile.incl

# End
